def inform_about_the_result(times):
    print(f"Tvoje číslo bylo vylosované po {times} pokusech.")

#def inform_about_the_result():
#    raise Exception